Repository vexxhost/ansible-collection-containers, pull requests merged in 2025-09, with the labels that each got.

#53 feat: bump all components + add automation
  .github/workflows/bump.yaml
  hack/bump/cni-plugins.sh
  hack/bump/containerd.sh
  hack/bump/cri-tools.sh
  hack/bump/lib.sh
  hack/bump/nerdctl.sh
  hack/bump/runc.sh
  roles/cni_plugins/defaults/main.yml
  roles/containerd/defaults/main.yml
  roles/containerd/templates/containerd.service.j2
  roles/cri_tools/defaults/main.yml
  roles/nerdctl/defaults/main.yml
  roles/runc/defaults/main.yml
Labels: feat

#55 chore: switch to py311
  .python-version
  plugins/action/binary_downloads.py
  pyproject.toml
  uv.lock
Labels: chore

#62 ci: add debian-13 basa job
  .zuul.yaml
Labels: ci
